---
title: "Project"
author: "Daniel Walker"
date: "4/30/2019"
output: html_document
---
```{r echo=TRUE, message=FALSE}
# always clean up R environment
rm (list = ls ())

#install.packages('RCurl')

# load all packages here
library (mdsr)
library(dplyr) # for data manipluation
library(ggplot2) # data visualization
library(reshape2) # reshaping 

# user-defined functions here (if any)

# load data

```

```{r}
# read data https://www.kaggle.com/starbucks/starbucks-menu
drinks_expanded <- read.csv('starbucks_drinkMenu_expanded.csv')
food <- read.csv('starbucks-menu-nutrition-food.csv')

# as the data seems to contains some trademarks and accent, we will first remove them
drinks_expanded$Beverage_category <- iconv(drinks_expanded$Beverage_category, "latin1", "ASCII", sub = "byte")
drinks_expanded$Beverage <- iconv(drinks_expanded$Beverage, "latin1", "ASCII", sub = "byte")
drinks_expanded$Beverage_prep <- iconv(drinks_expanded$Beverage_prep, "latin1", "ASCII", sub = "byte")

drinks_expanded$Beverage_category <- gsub('(<[a-z0-9]+>)','',drinks_expanded$Beverage_category)
drinks_expanded$Beverage <- gsub('(<[a-z0-9]+>)','',drinks_expanded$Beverage)
drinks_expanded$Beverage_prep <- gsub('(<[a-z0-9]+>)','',drinks_expanded$Beverage_prep)
```

### Quick view of Data
```{r}
head(food)
head(drinks_expanded)
```

### Plot Strar Bucks Food (Calories and Fat)
```{r}
# red line shows recomended meal amount of Calories for food
# blue line shows MAX recomended daily amount of Fat for Food

# https://www.uccs.edu/healthcircle/sites/healthcircle/files/inline-files/Meal%20Planning.pdf
# https://my.clevelandclinic.org/health/articles/11208-fat-what-you-need-to-know

plot(Calories~Fat, 
     ylab = 'Calories in Starbucks Food', 
     xlab = 'Fat in Starbucks Food',
     main = 'Caleries vs Fat for Starbucks Food', 
     data = food)
abline(v=22,col='blue')
abline(h=500,col='red')

food %>%
  select(Food.name,Calories,Fat) %>%
  filter(Calories>=500,Fat>=22) %>% 
  count(Food.name) %>% 
  ungroup() %>% 
  arrange(desc(n))

# Unhealthiest Option
food %>%
  select(Food.name,Calories,Fat) %>%
  filter(Calories>=600,Fat>=28) %>% 
  count(Food.name) %>% 
  ungroup() %>% 
  arrange(desc(n))
if(FALSE){
"
Green Goddess Avocado Salad			
Lentils & Vegetable Protein Bowl with Brown Rice		
Roasted Turkey & Dill Havarti Sandwich
"
}
```

### Plot Strar Bucks Drink (Calories and Total Fat)
```{r}
# red line shows recomended meal amount of Calories for food

# https://www.uccs.edu/healthcircle/sites/healthcircle/files/inline-files/Meal%20Planning.pdf
# https://my.clevelandclinic.org/health/articles/11208-fat-what-you-need-to-know

plot(Calories~Total_Fat, 
     ylab = 'Calories in Starbucks Drinks', 
     xlab = 'Total Fat in Starbucks Food',
     main = 'Caleries vs Total Fat for Starbucks Drinks', 
     data = drinks_expanded)
abline(h=500,col='red')
```