---
title: "STAT 380 Final Roject"
subtitle: "Spring 2019"
author: "SANCHIT GOEL"
date: "Due: 04/30/2019 11:59PM"
output: html_notebook
---

# Front matter
```{r}
# always clean up R environment
rm(list = ls())

# load all packages here
library(dplyr)
library(tidyr)
library(ggplot2)
library(caret)
library(ggplot2)
library(readr)
library(tidyverse)
library(ggthemes)
library(stringr)
library(repr)
library(plotly)

library(caTools)

# Setting a random seed
set.seed(1)
```
# Loading and Cleaning the Datasets
### McDonalds Dataset
```{r echo = F}
mcd <- read.csv(file = "nutrition_facts_mcdonalds_menu.csv", header = TRUE, sep = ",")
mcd[mcd == '-'] <- NA

print(paste0("Pre-Cleaning Records: ", nrow(mcd)))

# Dropping NA values records
mcd <- mcd %>%
  drop_na()

print(paste0("Cleaned Records: ", nrow(mcd)))

# Subsetting drinks from the menu
drinks.oz <- mcd[str_detect(mcd$Serving.Size, " fl oz.*"),]
drinks.ml <- mcd[str_detect(mcd$Serving.Size, 'carton'),]

# Converting ounces to mililiters and further rounding the values
drinks.oz$Serving.Size <- 
  round(as.numeric(gsub(" fl oz.*", "", drinks.oz$Serving.Size))*29.5735, 0)
drinks.ml$Serving.Size <- 
  round(as.numeric(gsub(".*\\((.*)\\ ml).*", "\\1", drinks.ml$Serving.Size)), 0)

# Keeping the values and removing characters
food.g <- mcd[str_detect(mcd$Serving.Size, 'g'),] 
food.g$Serving.Size <- 
  round(as.numeric(gsub(".*\\((.*)\\ g).*", "\\1", food.g$Serving.Size)), 0)

# Combining drinks and food menu
# While adding a new feature for drink or food
cleaned_mcd <- rbind(drinks.oz,drinks.ml)
cleaned_mcd$Type <- rep("drinks", nrow(cleaned_mcd))
food.g$Type <- rep("food", nrow(food.g))
cleaned_mcd <- rbind(cleaned_mcd,food.g)

rm("drinks.ml", "drinks.oz", "food.g")
```

### Starbucks Food Dataset
```{r echo = F}
sbux_f <- read.csv(file = "nutrition_facts_starbucks_food_menu.csv", header = TRUE, sep = ",")
sbux_f[sbux_f == '-'] <- NA

print(paste0("Pre-Cleaning Records: ", nrow(sbux_f)))
sbux_f <- sbux_f %>% 
  drop_na()

print(paste0("Cleaned Records: ", nrow(sbux_f)))
```

### Starbucks Drink Dataset
```{r echo = F}
sbux_d <- read.csv(file = "nutrition_facts_starbucks_drink_menu.csv", header = TRUE, sep = ",")
sbux_d[sbux_d == '-'] <- NA

print(paste0("Pre-Cleaning Records: ", nrow(sbux_d)))
sbux_d <- sbux_d %>% 
  drop_na()

print(paste0("Cleaned Records: ", nrow(sbux_d)))
```

### Starbucks Drink Expnaded Dataset
```{r echo = F}
sbux_de <- read.csv(file = "starbucks_drink_menu_expanded.csv", header = TRUE, sep = ",")
sbux_de[sbux_de == '-'] <- NA

print(paste0("Pre-Cleaning Records: ", nrow(sbux_de)))
sbux_de <- sbux_de %>% 
  drop_na()

print(paste0("Cleaned Records: ", nrow(sbux_de)))
```

### McDonalds Data Summary
```{r echo = F}
summary(mcd)
```

### Starbucks Food Data Summary
```{r echo = F}
summary(sbux_f)
```

### Starbucks Drink Data Summary
```{r echo = F}
summary(sbux_d)
```

### Starbucks Drink Expanded Data Summary
```{r echo = F}
summary(sbux_de)
```


## McDonalds:
#### Calories Histogram
```{r echo = F}
options(repr.plot.height = 3, repr.plot.width = 6)
ggplot(cleaned_mcd, aes(x = Calories)) +
  geom_histogram(aes(y = ..density..), fill = "lightblue", binwidth = 40, color = "darkgray") + 
  scale_x_continuous(breaks = seq(min(cleaned_mcd$Calories), max(cleaned_mcd$Calories), by = 200)) + 
  geom_density()
```

#### Calories BoxPlot
```{r echo = F}
options(repr.plot.height = 3, repr.plot.width = 6)
ggplot(cleaned_mcd, aes(x = reorder(Category, Calories), y = Calories)) +
  geom_boxplot() +
  coord_flip() +
  labs(x = NULL)
```

```{r}
# Splitting the dataset
split <- sample.split(cleaned_mcd$Calories, SplitRatio = 0.80)
train <- subset(cleaned_mcd, split == "TRUE")
test <- subset(cleaned_mcd, split == "FALSE")
```

```{r}
# Removing String Columns
df <- train %>% select(-Category, -Item, -Type)

# Setting Items as the outpput string type
rownames(df) <- train$Item

# Scaling the data and creating distance metrics using euclidean distance
dd <- dist(scale(df), method = "euclidean")

# Fitting hierarchical clustering
hc <- hclust(dd, method = "ward.D2")

# Plotting the results
plot(hc, hang = -1, cex = .25, cex.main = 2)
```

